name: 'build-test'
on:
  push:
    branches:
      - main
      - develop
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
      - run: npm install
      - run: npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          paths: '__tests__/sample-script.js User:SDZeroBot/deploy-test.js'
          apiUrl: 'https://test.wikipedia.org/w/api.php'
          oauth2Token: ${{ secrets.OAUTH2_TOKEN }}
